/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.LoginControl;
import Model.Funcionario;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author BETO
 */
public class Login extends javax.swing.JFrame {

    private final LoginControl controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        controller = new LoginControl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jLabelLogin1 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonSouAluno = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FitLife Academia");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(51, 51, 51));
        jLabelLogin.setText("Senha:");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabelLogin1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabelLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelLogin1.setText("Login:");
        getContentPane().add(jLabelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 220, 30));

        jButtonSouAluno.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButtonSouAluno.setText("Sou um aluno");
        jButtonSouAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSouAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSouAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 140, 30));

        jButtonLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLogin.setText("Entrar");
        jButtonLogin.setAlignmentY(0.0F);
        jButtonLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogin.setIconTextGap(0);
        jButtonLogin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLogin.setPreferredSize(new java.awt.Dimension(30, 20));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 70, 30));

        jTextFieldLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 220, 30));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundFinalFinal.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        //executa quando o botao eh clicado
        if(jTextFieldLogin.getText().equals("") && jPasswordField.getText().equals("")){
            this.controller.fizTarefa("Campos vazios!");
        }
        else if(jTextFieldLogin.getText().equals("")){
            this.controller.fizTarefa("Preencha o login!");
        }
        else if(jPasswordField.getText().equals("")){
            this.controller.fizTarefa("Informe a senha!");
        }
        
        int x = this.controller.logarNoSistema();
        if(x==3){
            DesktopSecretaria secretaria = new DesktopSecretaria();
            secretaria.setVisible(true);
            this.setVisible(false);
        } else if(x==2){
            DesktopInstrutor instrutorArea = new DesktopInstrutor();
            instrutorArea.setVisible(true);
            this.setVisible(false);
        } else if(x==4){
            exibeMensagem("Senha incorreta, tente novamente.");
        }
        else if(x==0){
            this.controller.fizTarefa("Usuario e senha invalidos!");
        } 
        else if(x==5){
            
        }


    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonSouAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSouAlunoActionPerformed
        DesktopAluno aluno = new DesktopAluno();
        aluno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSouAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSouAluno;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLogin1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public void setjPasswordField(JPasswordField jPasswordField) {
        this.jPasswordField = jPasswordField;
    }

    public JTextField getjTextFieldLogin() {
        return jTextFieldLogin;
    }

    public void setjTextFieldLogin(JTextField jTextFieldLogin) {
        this.jTextFieldLogin = jTextFieldLogin;
    }
    
    
    
}
